author: xXsuperman_YTXx
main: me.xxsuperman_ytxx.scc.Core
version: 1.2.3
name: SupermanChatCleaner
description: Foloseste acest plugin pentru a curata chatul!
commands:
  cgchat:
    description: Sterge chatul global.
    usage: /cghat
    aliases: [gchatc]
  cpchat:
    description: Sterge chatul personal.
    usage: /cphat
    aliases: [pchatc]
  cchat:
    description: Intra in meniul de Ajutor.
    usage: /cchat
    aliases: [cchelp]
  ccinfo:
    description: Intra in meniul de Informatii.
    usage: /ccinfo
    aliases: [cinfo]
  ccreload:
    description: ReIncarca configul Pluginului!
    usage: /ccreload
    aliases: [creload]